## Importing the Required Libraries

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import csv
import matplotlib as mp
import matplotlib.pyplot as plt
import mysql.connector as mysql
import os
from sodapy import Socrata
from sqlalchemy import create_engine

In [33]:
engine = create_engine('mysql+pymysql://root:Visionamd@23@localhost/montgomery')

In [34]:
socrata_domain = 'data.montgomerycountymd.gov'
socrata_dataset_identifier_drivers = 'mmzv-x632'
socrata_token = os.environ.get("SODAPY_APPTOKEN")
client = Socrata(socrata_domain, socrata_token)
results = client.get(socrata_dataset_identifier_drivers)
df = pd.DataFrame.from_dict(results)
 
# Use the filter method to select columns that don't start with ":@"
filtered_columns = df.filter(regex="^:@", axis=1)
columns_to_drop = ['latitude', 'longitude','geolocation']
# Drop the selected columns
df.drop(filtered_columns, axis=1, inplace=True)
df.drop(columns_to_drop, axis=1, inplace=True)
df.to_csv("drivers_1.csv", index=False)  # Save data to CSV file

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

## Reading Data into Variable Named Data From the CSV File

In [35]:
data = pd.read_csv("drivers_1.csv")

In [3]:
# data = pd.read_csv("Drivers_Data_20240404.csv")

/var/folders/_t/d0zkt0395w39b1mpx92kjmrw0000gn/T/ipykernel_56139/1262171991.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Drivers_Data_20240404.csv")

In [4]:
# Checking the input data which was imported from the csv into the data variable

In [5]:
data.head()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,NaN,NaN,NaN,NaN,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.150044,-77.063089,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,NaN,...,40,No,No,2011,GMC,TK,NO MISUSE,39.159264,-77.219025,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,NaN,...,35,No,No,2019,FORD,F150,NO MISUSE,39.109535,-77.075806,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,NaN,...,40,No,No,2016,KIA,SW,NO MISUSE,39.190149,-77.266766,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,NaN,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.172558,-77.203745,"(39.17255801, -77.20374546)"

## Creating Relational Database Connection MYSQL

In [6]:
# Establishing connection
connection = mysql.connect(
            host='localhost',
            user='root',
            password='Visionamd@23',
            database='montgomery'
)

if connection.is_connected():
    print("Connected to MySQL database")

Connected to MySQL database

In [7]:
connection

In [8]:
mycursor = connection.cursor()

## Relational Database Queries / DML Statements / DDL Statements

In [9]:
# Sql Statement for creation of table

In [10]:
querycreate = '''CREATE TABLE IF NOT EXISTS drivers_final(
   report_number text,
   local_case_number text,
   agency_name text,
   acrs_report_type text,
   crash_date_time text,
   route_type text,
   road_name text,
   cross_street_type text,
   cross_street_name text,
   off_road_description text,
   municipality text,
   related_non_motorist text,
   collision_type text,
   weather text,
   surface_condition text,
   light text,
   traffic_control text,
   driver_substance_abuse text,
   non_motorist_substance_abuse text,
   person_id text,
   driver_at_fault text,
   injury_severity text,
   circumstance text,
   driver_distracted_by text,
   drivers_license_state text,
   vehicle_id text,
   vehicle_damage_extent text,
   vehicle_first_impact_location text,
   vehicle_second_impact_location text,
   vehicle_body_type text,
   vehicle_movement text,
   vehicle_continuing_dir text,
   vehicle_going_dir text,
   speed_limit text,
   driverless_vehicle text,
   parked_vehicle text,
   vehicle_year text,
   vehicle_make text,
   vehicle_model text,
   equipment_problems text,
   latitude text,
   longitude text,
   location text
                )'''

In [11]:
mycursor.execute(querycreate) # executing/creating a table
connection.commit() # Commit the transaction

## Checking the Tables in the Database

In [12]:
mycursor.execute("SHOW TABLES")
tables = mycursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

drivers
drivers1
drivers_final

In [13]:
# Check Description of the drivers table
querydescribe="DESCRIBE drivers_final"

In [14]:
mycursor.execute(querydescribe)

In [15]:
columns=mycursor.fetchall()
for column in columns:
    print(column[0], "-", column[1])

report_number - text
local_case_number - text
agency_name - text
acrs_report_type - text
crash_date_time - text
route_type - text
road_name - text
cross_street_type - text
cross_street_name - text
off_road_description - text
municipality - text
related_non_motorist - text
collision_type - text
weather - text
surface_condition - text
light - text
traffic_control - text
driver_substance_abuse - text
non_motorist_substance_abuse - text
person_id - text
driver_at_fault - text
injury_severity - text
circumstance - text
driver_distracted_by - text
drivers_license_state - text
vehicle_id - text
vehicle_damage_extent - text
vehicle_first_impact_location - text
vehicle_second_impact_location - text
vehicle_body_type - text
vehicle_movement - text
vehicle_continuing_dir - text
vehicle_going_dir - text
speed_limit - text
driverless_vehicle - text
parked_vehicle - text
vehicle_year - text
vehicle_make - text
vehicle_model - text
equipment_problems - text

In [16]:
# Sql Statement for inserting data into the table

In [17]:
queryinsert = '''INSERT INTO drivers_final (
    report_number,
    local_case_number,
    agency_name,
    acrs_report_type,
    crash_date_time,
    route_type,
    road_name,
    cross_street_type,
    cross_street_name,
    off_road_description,
    municipality,
    related_non_motorist,
    collision_type,
    weather,
    surface_condition,
    light,
    traffic_control,
    driver_substance_abuse,
    non_motorist_substance_abuse,
    person_id,
    driver_at_fault,
    injury_severity,
    circumstance,
    driver_distracted_by,
    drivers_license_state,
    vehicle_id,
    vehicle_damage_extent,
    vehicle_first_impact_location,
    vehicle_second_impact_location,
    vehicle_body_type,
    vehicle_movement,
    vehicle_continuing_dir,
    vehicle_going_dir,
    speed_limit,
    driverless_vehicle,
    parked_vehicle,
    vehicle_year,
    vehicle_make,
    vehicle_model,
    equipment_problems,
    latitude,
    longitude,
    location
) VALUES ( %s,%s,%s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'''

In [18]:
df=data

In [19]:
print(df.dtypes)

Report Number                      object
Local Case Number                  object
Agency Name                        object
ACRS Report Type                   object
Crash Date/Time                    object
Route Type                         object
Road Name                          object
Cross-Street Type                  object
Cross-Street Name                  object
Off-Road Description               object
Municipality                       object
Related Non-Motorist               object
Collision Type                     object
Weather                            object
Surface Condition                  object
Light                              object
Traffic Control                    object
Driver Substance Abuse             object
Non-Motorist Substance Abuse       object
Person ID                          object
Driver At Fault                    object
Injury Severity                    object
Circumstance                       object
Driver Distracted By               object
Drivers License State              object
Vehicle ID                         object
Vehicle Damage Extent              object
Vehicle First Impact Location      object
Vehicle Second Impact Location     object
Vehicle Body Type                  object
Vehicle Movement                   object
Vehicle Continuing Dir             object
Vehicle Going Dir                  object
Speed Limit                         int64
Driverless Vehicle                 object
Parked Vehicle                     object
Vehicle Year                        int64
Vehicle Make                       object
Vehicle Model                      object
Equipment Problems                 object
Latitude                          float64
Longitude                         float64
Location                           object
dtype: object

## Filling Empty spaces with Missing

In [20]:
df_filled = data.fillna("Missing")

In [21]:
df_filled

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,Missing,Missing,Missing,Missing,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.150044,-77.063089,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,Missing,...,40,No,No,2011,GMC,TK,NO MISUSE,39.159264,-77.219025,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,Missing,...,35,No,No,2019,FORD,F150,NO MISUSE,39.109535,-77.075806,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,Missing,...,40,No,No,2016,KIA,SW,NO MISUSE,39.190149,-77.266766,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,Missing,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.172558,-77.203745,"(39.17255801, -77.20374546)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172100,DM8338000C,16010228,Takoma Park Police Depart,Property Damage Crash,01/03/2016 10:01:00 AM,Municipality,NEW HAMPSHIRE SERVICE LA,Municipality,PRINCE GEORGES AVE,Missing,...,25,No,No,2016,FORD,EXPLORER,NO MISUSE,38.972560,-76.997466,"(38.97255976, -76.99746609)"
172101,MCP1182001S,170519976,Montgomery County Police,Property Damage Crash,07/19/2017 02:22:00 PM,County,CEDAR LA,Maryland (State),OLD GEORGETOWN RD,Missing,...,35,No,No,2008,NISSAN,ALTIMA,NO MISUSE,39.004640,-77.108502,"(39.00464, -77.10850167)"
172102,MCP1453008X,200046217,Montgomery County Police,Property Damage Crash,11/23/2020 07:37:00 AM,Maryland (State),RIDGE RD,Unknown,LITTLE SENECA PKWY,Missing,...,40,No,No,2008,CHEVROLET,EXPRESS,NO MISUSE,39.228963,-77.236757,"(39.22896333, -77.23675667)"
172103,MCP2568000M,190056701,Montgomery County Police,Property Damage Crash,11/23/2019 11:23:00 PM,County,SHADY GROVE RD,Ramp,RAMP 9 FR IS 370 EB TO SHADY GROVE RD,Missing,...,35,No,No,2018,FORD,TRANSIT VAN,NO MISUSE,39.120440,-77.180047,"(39.12043995, -77.18004738)"
172104,MCP1048000P,15003337,Montgomery County Police,Property Damage Crash,01/21/2015 09:02:00 AM,Maryland (State),FREDERICK RD,Municipality,W GUDE DR,Missing,...,35,No,No,2011,HONDA,CRV,Missing,39.106847,-77.158380,"(39.10684667, -77.15838)"

In [22]:
# replacing all the values as strings in the data columns
df_filled.astype(str)

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,Missing,Missing,Missing,Missing,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.15004368,-77.06308884,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,Missing,...,40,No,No,2011,GMC,TK,NO MISUSE,39.1592635,-77.21902483,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,Missing,...,35,No,No,2019,FORD,F150,NO MISUSE,39.10953506,-77.07580619,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,Missing,...,40,No,No,2016,KIA,SW,NO MISUSE,39.19014917,-77.26676583,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,Missing,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.17255801,-77.20374546,"(39.17255801, -77.20374546)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172100,DM8338000C,16010228,Takoma Park Police Depart,Property Damage Crash,01/03/2016 10:01:00 AM,Municipality,NEW HAMPSHIRE SERVICE LA,Municipality,PRINCE GEORGES AVE,Missing,...,25,No,No,2016,FORD,EXPLORER,NO MISUSE,38.97255976,-76.99746609,"(38.97255976, -76.99746609)"
172101,MCP1182001S,170519976,Montgomery County Police,Property Damage Crash,07/19/2017 02:22:00 PM,County,CEDAR LA,Maryland (State),OLD GEORGETOWN RD,Missing,...,35,No,No,2008,NISSAN,ALTIMA,NO MISUSE,39.00464,-77.10850167,"(39.00464, -77.10850167)"
172102,MCP1453008X,200046217,Montgomery County Police,Property Damage Crash,11/23/2020 07:37:00 AM,Maryland (State),RIDGE RD,Unknown,LITTLE SENECA PKWY,Missing,...,40,No,No,2008,CHEVROLET,EXPRESS,NO MISUSE,39.22896333,-77.23675667,"(39.22896333, -77.23675667)"
172103,MCP2568000M,190056701,Montgomery County Police,Property Damage Crash,11/23/2019 11:23:00 PM,County,SHADY GROVE RD,Ramp,RAMP 9 FR IS 370 EB TO SHADY GROVE RD,Missing,...,35,No,No,2018,FORD,TRANSIT VAN,NO MISUSE,39.12043995,-77.18004738,"(39.12043995, -77.18004738)"
172104,MCP1048000P,15003337,Montgomery County Police,Property Damage Crash,01/21/2015 09:02:00 AM,Maryland (State),FREDERICK RD,Municipality,W GUDE DR,Missing,...,35,No,No,2011,HONDA,CRV,Missing,39.10684667,-77.15838,"(39.10684667, -77.15838)"

In [23]:
# Defining a variable to use as input counter

In [24]:
in_rec_cnt = 0

In [25]:
for index, row in df_filled.iterrows():
    mycursor.execute(queryinsert, tuple(row))
    in_rec_cnt += 1

ProgrammingError: 1054 (42S22): Unknown column 'latitude' in 'field list'

In [ ]:
connection.commit()

In [ ]:
print("Number of records inserted into table:", in_rec_cnt)

In [ ]:
mycursor.execute("SELECT COUNT(*) FROM drivers_final")
mycursor.fetchone()[0]

In [ ]:
querydropcol = '''ALTER TABLE drivers_final
DROP COLUMN Latitude,
DROP COLUMN Longitude,
DROP COLUMN Location'''

In [ ]:
mycursor.execute(querydropcol)

In [ ]:
connection.commit()

In [ ]:
# Execute the DESCRIBE query
mycursor.execute("DESCRIBE drivers_final")

# Fetch and print the column information
columns = mycursor.fetchall()
for column in columns:
    print(column)

In [ ]:
# Sql Statement for Visualisation of data inserted into the table

In [ ]:
queryshowtab = "SELECT * FROM drivers_final;"

In [ ]:
mycursor.execute(queryshowtab)
mycursor.fetchall()

In [ ]:
## Creating a SQl frame to read and edit data from the database

In [ ]:
sql_frame = pd.read_sql(queryshowtab, connection)

In [ ]:
sql_frame.head()

## Checking for duplicate records in the data.

In [ ]:
dup_rows = sql_frame.duplicated()
print("Number of duplicate rows:", dup_rows.sum())

In [ ]:
# There are no duplicates present in the data, if any, can drop using "sql_frame = sql_frame.drop_duplicates()" Command.

In [ ]:
## Check for Missing Values

In [ ]:
sql_frame.isnull().sum()

In [ ]:
# Since we've substituted 'NaN' with 'Missing', we'll now look for instances of 'Missing' in every column.

In [ ]:
# To check where "Missing" values occur in each column.
miss_mask = sql_frame.eq('Missing')

# Checking which columns have at least one "Missing" value.
col_miss = miss_mask.any()

# Extract the individual column names where "Missing" values appear.
col_miss_values = col_miss[col_miss].index.tolist()

# Print all the columns with "Missing" values.
print("Columns with 'Missing' values:", col_miss_values)

In [ ]:
# To count for the number of missing values in the above given columns.

In [ ]:
# Iterate through columns with missing values
for column in col_miss_values:
    # Get unique values and their counts
    uni_val_cnts = sql_frame[column].value_counts() 
    # Print column name
    print("Column:", column)
    # Print unique values and their counts
    print(uni_val_cnts)
    print()

In [ ]:
# Observing the Output for the each columns with the level of missing values and decision to keep or drop or replace the values

vehicle_damage_extent- 316 Missing and unknow "keep as is"

vehicle_first_impact_location - "Drop"

vehicle_second_impact_location - "Drop"

vehicle_body_type - "keep as is"

vehicle_movement - 386 fill with "Mode"

vehicle_continuing_dir - "Drop"

vehicle_going_dir - "Drop"

vehicle_make - "keep as is"

vehicle_model - "keep as is"

equipment_problems - "keep as is" 

For route_type - 16973 missing values and 20 unknown, which can be replaced by the "Mode"

For road_name - 15937 missing values can be filled with "Mode" or "keep as is"

For cross_street_type - 17006 missing values which can be replaced  with "Mode" or "keep as is"

For cross_street_name - 15951 missing values which can be replaced by the "Mode" 

For off_road_description - "Drop"

For municipality - "Drop"

For related_non_motorist - "Drop"

For collision_type - 585 missing values which can be replaced by "Mode"

For weather - 13354 missing values- "keep as is"

For surface_condition - 20118 missing values- "keep as is"

For light - 1445 missing values "keep as is"

traffic_control - 25469 Missing - "Mode"/"Drop"

driver_substance_abuse - 31324 Missing

non_motorist_substance_abuse - "Drop" 

circumstance - "Drop" 

drivers_license_state - 9950 "keep as is"

## Dropping columns with less importance

In [ ]:
col_to_drop = ['circumstance', 'non_motorist_substance_abuse', 'related_non_motorist','municipality','off_road_description','vehicle_first_impact_location','vehicle_second_impact_location','vehicle_continuing_dir','vehicle_going_dir']
sql_frame.drop(columns=col_to_drop, inplace=True)

In [ ]:
sql_frame.head()

In [ ]:
# Checking number of rows and columns after dropping the columns.

In [ ]:
num_rows, num_columns = sql_frame.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

In [ ]:
# Transforming the values with missing in the colums as required.

In [ ]:
#Replacing Missing with mode
sql_frame['vehicle_movement'] = sql_frame['vehicle_movement'].replace('Missing', sql_frame['vehicle_movement'].mode()[0])
sql_frame['route_type'] = sql_frame['route_type'].replace('Missing', sql_frame['route_type'].mode()[0])
sql_frame['road_name'] = sql_frame['road_name'].replace('Missing', sql_frame['road_name'].mode()[0])
sql_frame['cross_street_type'] = sql_frame['cross_street_type'].replace('Missing', sql_frame['cross_street_type'].mode()[0])
sql_frame['cross_street_name'] = sql_frame['cross_street_name'].replace('Missing', sql_frame['cross_street_name'].mode()[0])
sql_frame['collision_type'] = sql_frame['collision_type'].replace('Missing', sql_frame['collision_type'].mode()[0])

In [ ]:
sql_frame.head()

In [ ]:
# Count the number of columns containing 'Missing'
missing_columns_count = 0
missing_columns = []

for column in sql_frame.columns:
    if (sql_frame[column] == 'Missing').any():
        missing_count = (sql_frame[column] == 'Missing').sum()
        if missing_count > 0:
            missing_columns_count += 1
            missing_columns.append((column, missing_count))

print("Total number of columns with 'Missing' values:", missing_columns_count)
print("Columns with count of 'Missing' values:")
for column_name, count in missing_columns:
    print(f"{column_name}: {count}")

In [ ]:
final_transformed_frame=sql_frame

In [ ]:
new_df = sql_frame.head(5000)
filename = "drivers_final.json"
new_df .to_json(filename, orient='records')

In [ ]:
# Creating output file after commiting all the required transformation.
filename = "drivers.json"
final_transformed_frame.to_json(filename, orient='records')

## Mongo DB Connection

In [ ]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://x23236108:aasim123@montgomerycluster.tzxvtsd.mongodb.net/?retryWrites=true&w=majority&appName=montgomerycluster"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

try:
    #client.admin.command('ping')
    client.montgomery.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

In [ ]:
# checkig server status

In [ ]:
try:
    server_status = client.montgomery.command('serverStatus')
    print("Server is up and running.")
except Exception as e:
    print("Error:", e)

In [ ]:
# check databases.

In [ ]:
databases = client.list_database_names()
print("Databases:")
for db_obj in databases:
    print(db_obj)

In [ ]:
# checking all collections in mongo db

In [ ]:
database_name = "montgomery"
collections = client[database_name].list_collection_names()
print("\nCollections in", database_name, ":")
for col in collections:
    print(col)

In [ ]:
### Create database named montgomery and collection named driver

In [ ]:
db = client["montgomery"]

In [ ]:
database = 'montgomery'
dblist = client.list_database_names()
if database in dblist:
  print(f"The database {database} exists.")
  colList = db.list_collection_names()
  collection_name = 'drivers'
  if collection_name in colList:
      print(f"The collection { collection_name} exists.")
  else:
      print(f"The collection { collection_name } does NOT exists.")
      collection = db[ collection_name ]
else:
  print(f"The database {database} does not exists.")
  db = client[database]

In [ ]:
collections = client[database_name].list_collection_names()
print("\nCollections in", database_name, ":")
for col in collections:
    print(col)

## Loading JSON file onto incidents collection of montgomery database

In [ ]:
# Select database and collection
db = client['montgomery']
collections=db["drivers"]

# Get the total number of documents in the collection
total_records = collection.count_documents({})
print("Total number of records in the collection:", total_records)

In [ ]:
## Loading JSON file

In [ ]:
import json
filename = "drivers_final.json"
with open(filename, 'r') as file:
    data = json.load(file)

In [ ]:
# Insert documents into collection

In [ ]:
collection = db[collection_name]
collection.insert_many(data)
print("JSON data successfully loaded into MongoDB collection 'drivers_dupe' in database 'montgomery'.")
total_records = collection.count_documents({})
print("Total number of records in the collection:", total_records)

## Reading data for final analysis/visualization from MongoDB

In [ ]:
db = client["montgomery"]
collection = db["drivers"]
cursor = collection.find({})
mongo_frame = pd.DataFrame(list(cursor))

In [ ]:
mongo_frame.head()

## Visualising The data with individual columns.

In [ ]:
plt.hist(data=mongo_frame,x='Driver_At_Fault', bins=8, color='skyblue', edgecolor='black')

# Add labels and title
plt.xlabel('Driver_At_Fault')
plt.ylabel('Frequency')

# Show plot
plt.show()

## Visualisation of Crashes by Agency Names

In [ ]:
# Distribution of crashes by agency name
plt.figure(figsize=(10, 6))
sns.countplot(x='agency_name', data=mongo_frame)
plt.xticks(rotation=45)
plt.title('Crashes by Agency Name')
plt.show()

## Visualisation of Crash Frequency by Road Name and Cross Street Name.

In [ ]:
# Set the figure size
plt.figure(figsize=(12, 6))

# Plot for Crash frequency by road name
plt.subplot(1, 2, 1)
sns.countplot(y='road_name', data=mongo_frame, order=mongo_frame['road_name'].value_counts().index[:10])
plt.title('Crash Frequency by Road Name (Top 10)')
plt.xlabel('Frequency')
plt.ylabel('Road Name')

# Plot for Crash frequency by cross street name
plt.subplot(1, 2, 2)
sns.countplot(y='cross_street_name', data=mongo_frame, order=mongo_frame['cross_street_name'].value_counts().index[:10])
plt.title('Crash Frequency by Cross Street Name (Top 10)')
plt.xlabel('Frequency')
plt.ylabel('Cross Street Name')

# Adjust layout
plt.tight_layout()

# Show the plots
plt.show()

## Visualisation of Crashes over the years.

In [ ]:
# Time series analysis: Distribution of crashes over years
mongo_frame['crash_date_time'] = pd.to_datetime(mongo_frame['crash_date_time'])
mongo_frame['year'] = mongo_frame['crash_date_time'].dt.year
plt.figure(figsize=(10, 6))
sns.countplot(x='year', data=mongo_frame)
plt.title('Crashes Over Years')
plt.show()

## Visualisation of Crashes by ACRS Report Type

In [ ]:
# Calculate the counts for each ACRS report type
acrs_counts = mongo_frame['acrs_report_type'].value_counts()

# Plotting the pie chart
plt.figure(figsize=(8, 8))
plt.pie(acrs_counts, labels=acrs_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Crashes by ACRS Report Type')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

# Show the plot
plt.show()

## Visualisation of Driver with Injury Severity.

In [ ]:
# Set the figure size
plt.figure(figsize=(10, 6))

# Plot for Driver with Injury Severity
sns.countplot(y='injury_severity', data=mongo_frame, order=mongo_frame['injury_severity'].value_counts().index)
plt.title('Driver with Injury Severity')
plt.xlabel('Frequency')
plt.ylabel('Injury Severity')

# Show the plot
plt.show()

## Visualisation of Driver Substance Abuse

In [ ]:
# Driver Substance Abuse Distribution
plt.figure(figsize=(8, 8))
mongo_frame['driver_substance_abuse'].value_counts().plot(kind='pie',autopct='%1.1f%%')
plt.title('Proportion of Driver Substance Abuse')
plt.ylabel('')
plt.legend(bbox_to_anchor=(2, 0.5), loc="center left")
plt.tight_layout()
plt.show()