## Importing the Required Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import csv
import matplotlib as mp
import matplotlib.pyplot as plt
import mysql.connector as mysql
from sqlalchemy import create_engine

In [2]:
engine = create_engine('mysql+pymysql://root:Visionamd@23@localhost/montgomery')

## Reading Data into Variable Named Data From the CSV File

In [3]:
data = pd.read_csv("Drivers_Data_20240404.csv")

/var/folders/_t/d0zkt0395w39b1mpx92kjmrw0000gn/T/ipykernel_28407/1262171991.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Drivers_Data_20240404.csv")

In [4]:
# Checking the input data which was imported from the csv into the data variable

In [5]:
data.head()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,NaN,NaN,NaN,NaN,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.150044,-77.063089,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,NaN,...,40,No,No,2011,GMC,TK,NO MISUSE,39.159264,-77.219025,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,NaN,...,35,No,No,2019,FORD,F150,NO MISUSE,39.109535,-77.075806,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,NaN,...,40,No,No,2016,KIA,SW,NO MISUSE,39.190149,-77.266766,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,NaN,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.172558,-77.203745,"(39.17255801, -77.20374546)"

## Creating Relational Database Connection MYSQL

In [6]:
# Establishing connection
connection = mysql.connect(
            host='localhost',
            user='root',
            password='Visionamd@23',
            database='montgomery'
)

if connection.is_connected():
    print("Connected to MySQL database")

Connected to MySQL database

In [7]:
connection

In [8]:
mycursor = connection.cursor()

In [9]:
querycreate = '''CREATE TABLE IF NOT EXISTS drivers_final(
   report_number text,
   local_case_number text,
   agency_name text,
   acrs_report_type text,
   crash_date_time text,
   route_type text,
   road_name text,
   cross_street_type text,
   cross_street_name text,
   off_road_description text,
   municipality text,
   related_non_motorist text,
   collision_type text,
   weather text,
   surface_condition text,
   light text,
   traffic_control text,
   driver_substance_abuse text,
   non_motorist_substance_abuse text,
   person_id text,
   driver_at_fault text,
   injury_severity text,
   circumstance text,
   driver_distracted_by text,
   drivers_license_state text,
   vehicle_id text,
   vehicle_damage_extent text,
   vehicle_first_impact_location text,
   vehicle_second_impact_location text,
   vehicle_body_type text,
   vehicle_movement text,
   vehicle_continuing_dir text,
   vehicle_going_dir text,
   speed_limit text,
   driverless_vehicle text,
   parked_vehicle text,
   vehicle_year text,
   vehicle_make text,
   vehicle_model text,
   equipment_problems text,
   latitude text,
   longitude text,
   location text
                )'''

In [10]:
mycursor.execute(querycreate) # executing/creating a table
connection.commit() # Commit the transaction

In [11]:
mycursor.execute("SHOW TABLES")
tables = mycursor.fetchall()

# Print table names
for table in tables:
    print(table[0])

drivers
drivers1
drivers2
drivers_copy
drivers_final

In [12]:
# Check Description of the drivers table
querydescribe="DESCRIBE drivers_final"

In [13]:
mycursor.execute(querydescribe)

In [14]:
columns=mycursor.fetchall()
for column in columns:
    print(column[0], "-", column[1])

report_number - text
local_case_number - text
agency_name - text
acrs_report_type - text
crash_date_time - text
route_type - text
road_name - text
cross_street_type - text
cross_street_name - text
off_road_description - text
municipality - text
related_non_motorist - text
collision_type - text
weather - text
surface_condition - text
light - text
traffic_control - text
driver_substance_abuse - text
non_motorist_substance_abuse - text
person_id - text
driver_at_fault - text
injury_severity - text
circumstance - text
driver_distracted_by - text
drivers_license_state - text
vehicle_id - text
vehicle_damage_extent - text
vehicle_first_impact_location - text
vehicle_second_impact_location - text
vehicle_body_type - text
vehicle_movement - text
vehicle_continuing_dir - text
vehicle_going_dir - text
speed_limit - text
driverless_vehicle - text
parked_vehicle - text
vehicle_year - text
vehicle_make - text
vehicle_model - text
equipment_problems - text

In [15]:
queryinsert = '''INSERT INTO drivers_final (
    report_number,
    local_case_number,
    agency_name,
    acrs_report_type,
    crash_date_time,
    route_type,
    road_name,
    cross_street_type,
    cross_street_name,
    off_road_description,
    municipality,
    related_non_motorist,
    collision_type,
    weather,
    surface_condition,
    light,
    traffic_control,
    driver_substance_abuse,
    non_motorist_substance_abuse,
    person_id,
    driver_at_fault,
    injury_severity,
    circumstance,
    driver_distracted_by,
    drivers_license_state,
    vehicle_id,
    vehicle_damage_extent,
    vehicle_first_impact_location,
    vehicle_second_impact_location,
    vehicle_body_type,
    vehicle_movement,
    vehicle_continuing_dir,
    vehicle_going_dir,
    speed_limit,
    driverless_vehicle,
    parked_vehicle,
    vehicle_year,
    vehicle_make,
    vehicle_model,
    equipment_problems,
    latitude,
    longitude,
    location
) VALUES ( %s,%s,%s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'''

In [16]:
df=data

In [17]:
print(df.dtypes)

Report Number                      object
Local Case Number                  object
Agency Name                        object
ACRS Report Type                   object
Crash Date/Time                    object
Route Type                         object
Road Name                          object
Cross-Street Type                  object
Cross-Street Name                  object
Off-Road Description               object
Municipality                       object
Related Non-Motorist               object
Collision Type                     object
Weather                            object
Surface Condition                  object
Light                              object
Traffic Control                    object
Driver Substance Abuse             object
Non-Motorist Substance Abuse       object
Person ID                          object
Driver At Fault                    object
Injury Severity                    object
Circumstance                       object
Driver Distracted By               object
Drivers License State              object
Vehicle ID                         object
Vehicle Damage Extent              object
Vehicle First Impact Location      object
Vehicle Second Impact Location     object
Vehicle Body Type                  object
Vehicle Movement                   object
Vehicle Continuing Dir             object
Vehicle Going Dir                  object
Speed Limit                         int64
Driverless Vehicle                 object
Parked Vehicle                     object
Vehicle Year                        int64
Vehicle Make                       object
Vehicle Model                      object
Equipment Problems                 object
Latitude                          float64
Longitude                         float64
Location                           object
dtype: object

In [18]:
df_filled = data.fillna("Missing")

In [19]:
df_filled

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,Missing,Missing,Missing,Missing,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.150044,-77.063089,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,Missing,...,40,No,No,2011,GMC,TK,NO MISUSE,39.159264,-77.219025,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,Missing,...,35,No,No,2019,FORD,F150,NO MISUSE,39.109535,-77.075806,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,Missing,...,40,No,No,2016,KIA,SW,NO MISUSE,39.190149,-77.266766,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,Missing,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.172558,-77.203745,"(39.17255801, -77.20374546)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172100,DM8338000C,16010228,Takoma Park Police Depart,Property Damage Crash,01/03/2016 10:01:00 AM,Municipality,NEW HAMPSHIRE SERVICE LA,Municipality,PRINCE GEORGES AVE,Missing,...,25,No,No,2016,FORD,EXPLORER,NO MISUSE,38.972560,-76.997466,"(38.97255976, -76.99746609)"
172101,MCP1182001S,170519976,Montgomery County Police,Property Damage Crash,07/19/2017 02:22:00 PM,County,CEDAR LA,Maryland (State),OLD GEORGETOWN RD,Missing,...,35,No,No,2008,NISSAN,ALTIMA,NO MISUSE,39.004640,-77.108502,"(39.00464, -77.10850167)"
172102,MCP1453008X,200046217,Montgomery County Police,Property Damage Crash,11/23/2020 07:37:00 AM,Maryland (State),RIDGE RD,Unknown,LITTLE SENECA PKWY,Missing,...,40,No,No,2008,CHEVROLET,EXPRESS,NO MISUSE,39.228963,-77.236757,"(39.22896333, -77.23675667)"
172103,MCP2568000M,190056701,Montgomery County Police,Property Damage Crash,11/23/2019 11:23:00 PM,County,SHADY GROVE RD,Ramp,RAMP 9 FR IS 370 EB TO SHADY GROVE RD,Missing,...,35,No,No,2018,FORD,TRANSIT VAN,NO MISUSE,39.120440,-77.180047,"(39.12043995, -77.18004738)"
172104,MCP1048000P,15003337,Montgomery County Police,Property Damage Crash,01/21/2015 09:02:00 AM,Maryland (State),FREDERICK RD,Municipality,W GUDE DR,Missing,...,35,No,No,2011,HONDA,CRV,Missing,39.106847,-77.158380,"(39.10684667, -77.15838)"

In [20]:
# replacing all the values as strings in the data columns
df_filled.astype(str)

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,Missing,Missing,Missing,Missing,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.15004368,-77.06308884,"(39.15004368, -77.06308884)"
1,EJ78850038,230034791,Gaithersburg Police Depar,Property Damage Crash,07/21/2023 05:59:00 PM,Maryland (State),FREDERICK RD,Unknown,WATKINS MILL RD,Missing,...,40,No,No,2011,GMC,TK,NO MISUSE,39.1592635,-77.21902483,"(39.1592635, -77.21902483)"
2,MCP2009002G,230034583,Montgomery County Police,Property Damage Crash,07/20/2023 03:10:00 PM,Maryland (State),GEORGIA AVE,Maryland (State),NORBECK RD,Missing,...,35,No,No,2019,FORD,F150,NO MISUSE,39.10953506,-77.07580619,"(39.10953506, -77.07580619)"
3,MCP3201004C,230035036,Montgomery County Police,Property Damage Crash,07/23/2023 12:10:00 PM,County,CRYSTAL ROCK DR,County,WATERS LANDING DR,Missing,...,40,No,No,2016,KIA,SW,NO MISUSE,39.19014917,-77.26676583,"(39.19014917, -77.26676583)"
4,MCP23290028,230035152,Montgomery County Police,Property Damage Crash,07/24/2023 06:10:00 AM,County,MONTGOMERY VILLAGE AVE,County,CENTERWAY RD,Missing,...,35,No,No,2016,TOYT,TK,NO MISUSE,39.17255801,-77.20374546,"(39.17255801, -77.20374546)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172100,DM8338000C,16010228,Takoma Park Police Depart,Property Damage Crash,01/03/2016 10:01:00 AM,Municipality,NEW HAMPSHIRE SERVICE LA,Municipality,PRINCE GEORGES AVE,Missing,...,25,No,No,2016,FORD,EXPLORER,NO MISUSE,38.97255976,-76.99746609,"(38.97255976, -76.99746609)"
172101,MCP1182001S,170519976,Montgomery County Police,Property Damage Crash,07/19/2017 02:22:00 PM,County,CEDAR LA,Maryland (State),OLD GEORGETOWN RD,Missing,...,35,No,No,2008,NISSAN,ALTIMA,NO MISUSE,39.00464,-77.10850167,"(39.00464, -77.10850167)"
172102,MCP1453008X,200046217,Montgomery County Police,Property Damage Crash,11/23/2020 07:37:00 AM,Maryland (State),RIDGE RD,Unknown,LITTLE SENECA PKWY,Missing,...,40,No,No,2008,CHEVROLET,EXPRESS,NO MISUSE,39.22896333,-77.23675667,"(39.22896333, -77.23675667)"
172103,MCP2568000M,190056701,Montgomery County Police,Property Damage Crash,11/23/2019 11:23:00 PM,County,SHADY GROVE RD,Ramp,RAMP 9 FR IS 370 EB TO SHADY GROVE RD,Missing,...,35,No,No,2018,FORD,TRANSIT VAN,NO MISUSE,39.12043995,-77.18004738,"(39.12043995, -77.18004738)"
172104,MCP1048000P,15003337,Montgomery County Police,Property Damage Crash,01/21/2015 09:02:00 AM,Maryland (State),FREDERICK RD,Municipality,W GUDE DR,Missing,...,35,No,No,2011,HONDA,CRV,Missing,39.10684667,-77.15838,"(39.10684667, -77.15838)"

In [21]:
in_rec_cnt = 0

In [22]:
for index, row in df_filled.iterrows():
    mycursor.execute(queryinsert, tuple(row))
    in_rec_cnt += 1

ProgrammingError: 1054 (42S22): Unknown column 'latitude' in 'field list'

In [ ]:
connection.commit()

In [ ]:
print("Number of records inserted into table:", in_rec_cnt)

In [ ]:
mycursor.execute("SELECT COUNT(*) FROM drivers_final")
mycursor.fetchone()[0]

In [ ]:
querydropcol = '''ALTER TABLE drivers_final
DROP COLUMN Latitude,
DROP COLUMN Longitude,
DROP COLUMN Location'''

In [ ]:
mycursor.execute(querydropcol)

In [ ]:
connection.commit()

In [ ]:
# Execute the DESCRIBE query
mycursor.execute("DESCRIBE drivers_final")

# Fetch and print the column information
columns = mycursor.fetchall()
for column in columns:
    print(column)

In [ ]:
queryshowtab = "SELECT * FROM drivers_final;"

In [ ]:
mycursor.execute(queryshowtab)
mycursor.fetchall()

In [ ]:
cur = connection.cursor()
for index, row in df_filled.iterrows():
    cur.execute(queryinsert, tuple(row))

In [ ]:
duplicate_rows = sql_frame.duplicated()
print("Number of duplicate rows:", duplicate_rows.sum())

In [ ]:
sql_frame.isnull().sum()

In [ ]:
# Iterate through columns with missing values
for column in columns_with_missing_values:
    # Get unique values and their counts
    unique_values_counts = sql_frame[column].value_counts() 
    # Print column name
    print("Column:", column)
    # Print unique values and their counts
    print(unique_values_counts)
    print()

In [ ]:
# Check where "Missing" values occur in each column
missing_mask = sql_frame.eq('Missing')

# Check which columns have at least one "Missing" value
columns_with_missing = missing_mask.any()

# Extract the column names where "Missing" values occur
columns_with_missing_values = columns_with_missing[columns_with_missing].index.tolist()

# Print the columns with "Missing" values
print("Columns with 'Missing' values:", columns_with_missing_values)

In [ ]:
cursor =connection.cursor()
cursor.execucur = connection.cursor()(queryinsert)

In [ ]:
cursor = conn.cursor()
cursor.execute(drop_columns)
# Commit the transaction
conn.commit()